### ISSUE TITLE
Tutorial disappeared from azure.microsoft.com

### ISSUE THREAD

**Issue by shpros** [Azure-Samples/key-vault-node-getting-started#2]
This isn't a problem with this repo, per se, but with the page that used to display the README content. As recently as yesterday, this tutorial used to be available at https://azure.microsoft.com/en-us/resources/samples/key-vault-node-getting-started/ , but today that link gives a 404, and I can't find where it might have moved to.

**Comment by amarzavery** [comment]
@allclark can you look into this issue? Or can you loop in someone who maintains the doc site to find out why the link is giving 404?

**Comment by shpros** [comment]
The tutorial reappeared this morning, so I'll go ahead and close this issue. Thanks for poking the responsible people.
